remote_theme: pages-themes/midnight@v0.2.0
plugins: 
- jekyll-remote-theme # add this line to the plugins list if you already have it 
gem "github-pages", group: :jekyll_plugins
title: root💀senseicat:~#
description: Hack. Eat. Sleep. Repeat!!!
show_downloads: false
show_repo: false

gems:
- jekyll-sitemap

whitelist:
- jekyll-sitemap
